//
//  RecipeData.swift
//  breakfast
//
//  Created by Andrew Foster on 3/22/17.
//  Copyright © 2017 Andrii Halabuda. All rights reserved.
//

import Foundation
import UIKit

let r1 = Recipe(recipeTitle: "Oatmeal", recipeDescription: "Both types of rolled oats may be eaten uncooked, as in muesli, or may be cooked with water to make porridge. In some countries, rolled oats are eaten raw with milk and sugar, sometimes with raisins added, like a basic muesli. Porridge is served in many ways. Steel-cut oats, which take about 15 minutes to cook, contain more fiber than rolled oats or instant varieties, but any type of oatmeal is a healthy choice. Just avoid the flavored kinds, which can be packed with sugar. Instead, sweeten your bowl with milk and a bit of honey, and top with fruit and nuts.")
let r2 = Recipe(recipeTitle: "Yogurt", recipeDescription: "Yogurt is often included on healthy food lists and for good reason. Yogurt is highly nutritious and is an excellent source of protein, calcium and potassium. It provides numerous vitamins and minerals and is relatively low in calories. Some consumers are choosing Greek yogurt because of its creamier texture and higher protein content. Both Greek yogurt and regular yogurt contribute to a healthy diet. Greek yogurt has about twice the protein, half the sodium and half the carbohydrates as regular yogurt. Both products start with the same raw ingredient—milk.")
let r3 = Recipe(recipeTitle: "Grapefruit", recipeDescription: "Grapefruits are low in calories but are full of nutrients and an excellent source of vitamins A and C. Grapefruit is an excellent source of vitamin C, a vitamin that helps to support the immune system. Vitamin C-rich foods like grapefruit may help reduce cold symptoms or severity of cold symptoms; over 20 scientific studies have suggested that vitamin C is a cold-fighter. Vitamin C also prevents the free radical damage that triggers the inflammatory cascade, and is therefore also associated with reduced severity of inflammatory conditions, such as asthma, osteoarthritis, and rheumatoid arthritis. As free radicals can oxidize cholesterol and lead to plaques that may rupture causing heart attacks or stroke, vitamin C is beneficial to promoting cardiovascular health.")
let r4 = Recipe(recipeTitle: "Banana", recipeDescription: "Bananas are rich in a mineral called potassium. This mineral is important as it helps maintain fluid levels in the body and regulates the movement of nutrients and waste products in and out of cells. Potassium also helps muscles to contract and nerve cells to respond. It keeps the heart beating regularly and can reduce the effect of sodium on blood pressure. Potassium may reduce the risk of kidney stones forming as people age. In turn, healthy kidneys make sure that the right amount of potassium is kept in the body. One medium-sized banana contains 422 milligrams of potassium.")
let r5 = Recipe(recipeTitle: "Eggs", recipeDescription: "Eggs are among the most nutritious foods on the planet. Eggs are widely used in many types of dishes, both sweet and savory, including many baked goods. Some of the most common preparation methods include scrambled, fried, hard-boiled, soft-boiled, omelettes and pickled. Chicken eggs, the most commonly eaten eggs, provide 155 calories (kcal) of food energy and 12.6 g of protein in a 100 gram serving. ")
let r6 = Recipe(recipeTitle: "Watermelon", recipeDescription: "As its name suggests, watermelon is an excellent way to hydrate in the morning. What's less well known is this juicy fruit is among the best sources of lycopene—a nutrient found in red fruits and vegetables that's important for vision, heart health, and cancer prevention. Best of all, watermelon contains just 40 calories per cup, landing it on lists of so-called negative-calorie foods that supposedly burn more calories during digestion than they add in. Despite popular belief that watermelon is made up of only water and sugar, watermelon is actually considered a nutrient dense food, a food that provides a high amount of vitamins, minerals and antioxidants for a low amount of calories.")
let r7 = Recipe(recipeTitle: "Strawberries", recipeDescription: "Berries are superfoods because they're so high in antioxidants without being high in calories. One cup of strawberries, for instance, contains your full recommended daily intake of vitamin C, along with high quantities of folic acid and fiber. In addition to being consumed fresh, strawberries can be frozen, made into preserves, as well as dried and used in prepared foods, such as cereal bars. Strawberries and strawberry flavorings are a popular addition to dairy products, such as strawberry-flavored milk, strawberry ice cream, strawberry milkshakes, strawberry smoothies and strawberry yogurts.")
let r8 = Recipe(recipeTitle: "Coffee", recipeDescription: "Coffee is actually very healthy. It is loaded with antioxidants and beneficial nutrients that can improve your health. The studies show that coffee drinkers have a much lower risk of several serious diseases. Coffee is a brewed drink prepared from roasted coffee beans, which are the seeds of berries from the Coffea plant.")
let r9 = Recipe(recipeTitle: "Tea", recipeDescription: "Tea has a pretty impressive health benefits. Because it has less caffeine, it hydrates you more effectively than coffee, and it's also a rich source of the immunity-boosting antioxidants known as catechins. All tea (black, green, or white) provides antioxidants, but green tea may be healthiest of all. Research suggests that drinking five cups a day can increase your body's metabolism and help you lose more weight around the middle.")
let r10 = Recipe(recipeTitle: "Pancakes", recipeDescription: "Pancakes are a favorite breakfast food, and many varieties provide a number of essential nutrients. However, they can be high in calories from sugar and fat, especially if you eat them at a restaurant and if you top them with a lot of butter and syrup. A pancake (or hotcake, griddlecake, or flapjack) is a flat cake, often thin and round, prepared from a starch-based batter that may contain eggs, milk and butter and cooked on a hot surface such as a griddle or frying pan, often frying with oil or butter.")
